# Generated by Django 3.2.4 on 2021-07-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_defencearticle_mlarticle_nondefencearticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='heading',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='defencearticle',
            name='heading',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='mlarticle',
            name='heading',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='nondefencearticle',
            name='heading',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
