# Generated by Django 3.2.4 on 2021-07-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210714_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIdefenceArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255, unique=True)),
                ('url', models.URLField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AInonDefenceArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255, unique=True)),
                ('url', models.URLField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
