# Generated by Django 3.2.4 on 2021-07-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_mlarticle_unclassiedarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidefencearticle',
            name='date',
            field=models.CharField(default='aaj', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ainondefencearticle',
            name='date',
            field=models.CharField(default='aaj', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.CharField(default='aaj', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defencearticle',
            name='date',
            field=models.CharField(default='aaj', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nondefencearticle',
            name='date',
            field=models.CharField(default='aaj', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unclassiedarticle',
            name='date',
            field=models.CharField(default='aaj', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
