# Generated by Django 3.2.4 on 2021-07-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210723_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidefencearticle',
            name='date',
            field=models.TextField(default='10\x08\x08'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ainondefencearticle',
            name='date',
            field=models.TextField(default='aj'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.TextField(default='kl'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defencearticle',
            name='date',
            field=models.TextField(default='kl'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nondefencearticle',
            name='date',
            field=models.TextField(default='kl'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unclassiedarticle',
            name='date',
            field=models.TextField(default='kl'),
            preserve_default=False,
        ),
    ]
